---
title: "p8105_hw6_tb2715"
author: "Tess"
date: "11/16/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(viridis)
library(purrr)
library(modelr)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

## Question 1
```{r}
birthweight_data = read_csv("./data/birthweight.csv")

birthweight_data %>%
  janitor:: clean_names() %>%
   mutate(
    babysex = as.factor(babysex),
    frace = as.factor(frace),
    malform = as.factor(malform),
    mrace = as.factor(mrace)
  )
```

```{r}
# create univariate linear model with menarche
fincome_effect = lm(bwt ~ fincome, data = birthweight_data) 

fincome_effect %>%
  broom::tidy() %>%
  knitr::kable(digits = 2)
```
In a simple, unadjusted linear regression model, family monthly income (continuous variable) is a significant predictor of birthweight, such that birthweight increases with increasing family monthly income.

```{r}
birthweight_data %>%
  add_residuals(fincome_effect) %>%
  add_predictions(fincome_effect) %>%
  ggplot(aes(x = bwt, y = resid)) + geom_violin()

```

```{r}
#create 2 comparison linear models
main_effects = lm(bwt ~ blength + gaweeks, data = birthweight_data) %>%
  broom::tidy()

main_effects

all_effects = lm(bwt ~ bhead * blength * babysex, data = birthweight_data) %>%
  broom::tidy()

all_effects

crossv_mc(birthweight_data, 4342, test = 0.2)
```


## Question 2
# Import weather data
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

# Create function to bootstrap
```{r}
boot_sample = function(df) {
  sample_frac(df, replace = TRUE)
}
```

#run bootstrep
```{r}
boot_straps = 
  data_frame(
    strap_number = 1:5000,
    strap_sample = rerun(5000, boot_sample(weather_df))
  )

boot_straps
```

```{r}
bootstrap_results = 
  boot_straps %>% 
  mutate(
    models = map(strap_sample, ~lm(tmax ~ tmin, data = .x)),
    results = map(models, broom::tidy)) %>% 
  select(-strap_sample, -models) %>% 
  unnest() 



boot_straps %>% 
  unnest(strap_sample) %>% 
  ggplot(aes(tmin = tmin, tmax = tmax)) + 
  geom_line(aes(group = strap_number), stat = "smooth", method = "lm", se = FALSE, alpha = .1, color = "blue") +
  geom_point(data = weather_df, alpha = .5)


ggplot %>% 
  ggplot(aes(tmin = tmin, tmax = tmax)) + 
  geom_line(aes(group = strap_number), stat = "smooth", method = "lm", se = FALSE, alpha = .1, color = "blue") +
  geom_point(data = weather_df, alpha = .5)

  group_by(term) %>% 
  summarize(boot_se = sd(estimate))
```

